name: deepcopy
description: simple recursive deep copy for nested collections (List, Set, Map)
version: 1.1.2
repository: https://github.com/letyletylety/deepcopy
issue_tracker: https://github.com/letyletylety/deepcopy/issues
topics:
  - deepcopy
  - collection

environment:
  sdk: '>=3.0.5 <4.0.0'
  # flutter: '>=1.17.0'

dependencies:
  # flutter:
  #   sdk: flutter

dev_dependencies:
  fast_immutable_collections: ^9.1.5
  test: ^1.24.4

  benchmark_harness: ^2.2.2

screenshots:
  - description: The package logo.
    path: logos/deepcopy_logo@4x.png
